language: java

dist: trusty

jdk:
  - oraclejdk9

addons:
  apt:
    packages:
    - junit4
    - libmockito-java

script:
  - make
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)